import streamlit as st
import cv2
from ultralytics import YOLO
import pandas as pd
from datetime import datetime
import time

# --- CONFIGURATION ---
# Paste the HTTPS address generated by your new Ngrok HTTP tunnel here
# Make sure to append '/video' at the end of the URL string
HTTP_STREAM_URL = "https://bulk-boxer-handiness.ngrok-free.dev/video"

@st.cache_resource
def load_model():
    return YOLO("yolov8n.pt")

model = load_model()

st.set_page_config(page_title="Live Camera Analysis", layout="wide")
st.title("📹 Deployed Live Video Analysis Dashboard")

if "running" not in st.session_state:
    st.session_state.running = False
if "log_data" not in st.session_state:
    st.session_state.log_data = []

# Controls
st.sidebar.header("Controls")
if st.sidebar.button("▶️ Start Stream"):
    st.session_state.running = True
if st.sidebar.button("⏹️ Stop Stream"):
    st.session_state.running = False

col1, col2 = st.columns([2, 1])
with col1:
    frame_placeholder = st.empty()
with col2:
    metric_placeholder = st.empty()
    table_placeholder = st.empty()

# --- PROCESSING LOOP ---
if st.session_state.running:
    # OpenCV natively opens MJPEG HTTP streams seamlessly without protocol errors
    cap = cv2.VideoCapture(HTTP_STREAM_URL)
    
    if not cap.isOpened():
        st.error("Cloud Error: Cannot reach the Ngrok HTTP stream pipeline. Verify local scripts are running.")
        st.session_state.running = False

    while cap.isOpened() and st.session_state.running:
        ret, frame = cap.read()
        if not ret:
            st.warning("Frame dropped or stream ended.")
            break

        # ML Inference
        results = model(frame, verbose=False, classes=0)
        human_count = len(results[0].boxes) if results else 0

        for result in results:
            for box in result.boxes:
                x1, y1, x2, y2 = map(int, box.xyxy[0])
                cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)

        # Dashboard rendering
        frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frame_placeholder.image(frame_rgb, channels="RGB", use_column_width=True)
        
        current_time = datetime.now().strftime("%H:%M:%S")
        metric_placeholder.metric(label="Humans Detected", value=human_count)

        if human_count > 0:
            st.session_state.log_data.insert(0, {"Timestamp": current_time, "Count": human_count})
            st.session_state.log_data = st.session_state.log_data[:50]
            table_placeholder.dataframe(pd.DataFrame(st.session_state.log_data), use_container_width=True)

        time.sleep(0.01)
    cap.release()
else:
    frame_placeholder.info("Stream offline.")
